import math
import random

from panda3d.core import NodePath, PandaNode
from panda3d.core import Point3, Vec3, LColor

from noise import PerlinCurlNoise3D


def nonzero_random(a, b):
    while True:
        if (num := round(random.uniform(a, b))) != 0:
            return num


class RotationalComponent:
    """A class that uses PerlincurlNoise to calculate the force
       to be added to each particle's coordinates.
        Args:
            offset_1, offset2 (list):
                Offset the values significantly to avoid discontinuities.
                For example: offset_1 = [100, 200, 300], offset_2 = [500, 600, 700]
            noise_scale (float):
                The larger the noise_scale, the greater the particle motion.
                Must be non-zero
            flow_strength (float):
                The magnitude of the force generated by the vector field.
                The larger the value, the faster the particle moves.
                Must be non-zero
    """

    def __init__(self, offset_1, offset_2, noise_scale=1.05, flow_strength=3):
        self.noise_scale = noise_scale
        self.flow_strength = flow_strength
        self.noise = PerlinCurlNoise3D(offset_1, offset_2)

    def compute(self, pos, dt):
        curl = self.noise.curl_3d(*(pos * self.noise_scale))
        return curl * self.flow_strength * dt

    def __repr__(self):
        return f'noise_scale: {self.noise_scale}, flow_strength: {self.flow_strength}'


class BoxModel(NodePath):

    angular_speeds = [20, 40, 60, 80, 100]

    def __init__(self, serial, model, pos, color, rotational_component, scale_speed=0.5):
        super().__init__(PandaNode(f'box_{serial}'))
        model.copy_to(self)
        self.set_pos(pos)
        self.set_color(color, 1)
        self.set_flags()

        self.rotational_component = rotational_component
        self.scale_speed = scale_speed
        self.default_pos = pos

    def set_flags(self):
        self.outof_range = False
        self.disappeared = False

    def reset_np(self):
        self.set_pos_hpr_scale(self.default_pos, Vec3(0), Vec3(1))
        self.set_flags()

    def move(self, dt, time_limit):
        if self.disappeared:
            return False

        if (scale := self.get_scale() - self.scale_speed * dt) <= 0:
            self.detach_node()
            self.disappeared = True
            return False

        pos = self.get_pos()
        vec = self.rotational_component.compute(pos, dt)
        next_pos = pos + Vec3(*vec)

        angular_speed = random.choice(BoxModel.angular_speeds)
        hpr = self.get_hpr() + Vec3(angular_speed * dt)

        if not self.outof_range:
            if math.hypot(*(next_pos - self.default_pos)) > 0.2 or time_limit:
                self.outof_range = True

            self.set_pos_hpr(next_pos, hpr)
            return True

        self.set_pos_hpr_scale(next_pos, hpr, scale)
        return True


class BoxCollection:

    def __init__(self):
        self.collection = NodePath('collection')
        self.collection.set_pos(Point3(0, 0, 0))
        self.collection.reparent_to(base.render)
        self.time_limit = 6
        self.boxes = []
        self.set_flags()

    def set_flags(self):
        self.total_time = 0
        self.all_detached = False

    def create(self, noise_scale=1.05, flow_strength=3):
        start = -0.575
        count = 15

        model = base.loader.load_model('models/box.bam')
        end, tip = model.get_tight_bounds()
        box_size = tip - end
        color = LColor(1, 0, 0, 1)

        self.rotational_component = RotationalComponent(
            [0, 0, 300], [0, 0, 600], noise_scale, flow_strength)
        print(self.rotational_component)

        for i in range(count):
            z = i * box_size.z + start
            for j in range(count):
                y = j * box_size.y + start
                for k in range(count):
                    x = k * box_size.x + start
                    pos = Point3(x, y, z)
                    serial = f'{i}{j}{k}'
                    box = BoxModel(serial, model, pos, color, self.rotational_component)
                    box.reparent_to(self.collection)
                    self.boxes.append(box)

        self.collection.set_h(45)

    def reset(self):
        self.rotational_component.noise_scale = random.uniform(0.9, 3)
        self.rotational_component.flow_strength = nonzero_random(-3, 3)
        print(self.rotational_component)

        for box in self.boxes:
            box.reset_np()
            box.reparent_to(self.collection)

        self.set_flags()

    def move(self, dt):
        moved_box = 0
        self.total_time += dt

        for box in self.boxes:
            if box.move(dt, self.total_time >= self.time_limit):
                moved_box += 1

        if not moved_box:
            print('Finish.')
            self.all_detached = True
            return self.all_detached